"""
General script to generate UMAP visualization plots for all datasets and embeddings.
Visualizes 2D clusters from UMAP projections of raw data, PCA embeddings, and VAE embeddings.
Uses ModelData generated by generate_model_data.py.
"""
import pickle
import torch
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

from generate_model_data import ModelData


def plot_three_umaps(X1, labels1, X2, labels2, X3, labels3, 
                     title1='Raw Data', title2='PCA Embedding', title3='VAE Embedding',
                     modelname='', dataset_name='', output_dir='images/umaps', filename_suffix=''):
    """
    Plot three UMAP projections side by side for comparison.
    
    Args:
        X1, X2, X3: UMAP coordinates (numpy arrays or torch tensors, shape: [n_samples, 2])
        labels1, labels2, labels3: Labels for coloring
        title1, title2, title3: Plot titles
        modelname: Model name
        dataset_name: Dataset name
        output_dir: Output directory
        filename_suffix: Additional suffix for filename
    """
    # Convert to numpy if needed
    X1 = X1.cpu().numpy() if isinstance(X1, torch.Tensor) else X1
    labels1 = labels1.cpu().numpy() if isinstance(labels1, torch.Tensor) else labels1
    X2 = X2.cpu().numpy() if isinstance(X2, torch.Tensor) else X2
    labels2 = labels2.cpu().numpy() if isinstance(labels2, torch.Tensor) else labels2
    X3 = X3.cpu().numpy() if isinstance(X3, torch.Tensor) else X3
    labels3 = labels3.cpu().numpy() if isinstance(labels3, torch.Tensor) else labels3

    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    
    # Plot 1: Raw Data
    sc1 = axes[0].scatter(X1[:, 0], X1[:, 1], c=labels1, cmap='tab10', s=10, alpha=0.6)
    axes[0].set_title(title1, fontsize=12)
    axes[0].set_xlabel('UMAP 1')
    axes[0].set_ylabel('UMAP 2')
    plt.colorbar(sc1, ax=axes[0], label='Class')

    # Plot 2: PCA Embedding
    sc2 = axes[1].scatter(X2[:, 0], X2[:, 1], c=labels2, cmap='tab10', s=10, alpha=0.6)
    axes[1].set_title(title2, fontsize=12)
    axes[1].set_xlabel('UMAP 1')
    axes[1].set_ylabel('UMAP 2')
    plt.colorbar(sc2, ax=axes[1], label='Class')

    # Plot 3: VAE Embedding (highlighted)
    sc3 = axes[2].scatter(X3[:, 0], X3[:, 1], c=labels3, cmap='tab10', s=10, alpha=0.6)
    axes[2].set_title(title3, fontsize=12, fontweight='bold', color='#2E86AB')
    axes[2].set_xlabel('UMAP 1')
    axes[2].set_ylabel('UMAP 2')
    plt.colorbar(sc3, ax=axes[2], label='Class')

    fig.suptitle(f'{modelname} - {dataset_name}', fontsize=14, y=1.02)
    plt.tight_layout()
    
    # Create filename
    safe_title1 = title1.replace(' ', '_').lower()
    safe_title2 = title2.replace(' ', '_').lower()
    safe_title3 = title3.replace(' ', '_').lower()
    safe_modelname = modelname.replace('.pth', '').replace('.', '_')
    filename = f'{safe_modelname}_{safe_title1}_{safe_title2}_{safe_title3}'
    if filename_suffix:
        filename += f'_{filename_suffix}'
    filename += '.pdf'
    
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    filepath = output_path / filename
    
    plt.savefig(filepath, format='pdf', bbox_inches='tight')
    plt.close()
    print(f'      Saved to {filepath}')


def process_model_data(model_data_path, output_dir='images/umaps'):
    """
    Process a single ModelData file and generate three-way UMAP plot.
    
    Args:
        model_data_path: Path to pickled ModelData file
        output_dir: Output directory for images
    """
    print(f'\n{"="*60}')
    print(f'Processing: {model_data_path}')
    print(f'{"="*60}')
    
    # Load model data
    with open(model_data_path, 'rb') as f:
        model_data = pickle.load(f)
    
    dataset_name = model_data.dataset_name
    model_name = model_data.model_name
    
    print(f'Dataset: {dataset_name}')
    print(f'Model: {model_name}')
    
    # Get UMAP data and labels
    umap_data = {
        'Raw': model_data.umap_raw,
        'PCA': model_data.umap_pca,
        'VAE': model_data.umap_vae,
    }
    
    labels = model_data.labels
    
    # Check which UMAPs are available
    available_umaps = {k: v for k, v in umap_data.items() if v is not None}
    
    if len(available_umaps) == 0:
        print('    No UMAP data available')
        return
    
    print(f'    Available UMAP types: {list(available_umaps.keys())}')
    
    # Plot all three together
    if len(available_umaps) >= 3:
        print('    Generating three-way UMAP comparison...')
        # Try to get Raw, PCA, VAE in that order
        umap_order = ['Raw', 'PCA', 'VAE']
        coords_list = []
        names_list = []
        
        for name in umap_order:
            if name in available_umaps:
                coords_list.append(available_umaps[name])
                names_list.append(name)
        
        if len(coords_list) == 3:
            try:
                plot_three_umaps(
                    X1=coords_list[0],
                    labels1=labels,
                    X2=coords_list[1],
                    labels2=labels,
                    X3=coords_list[2],
                    labels3=labels,
                    title1='Raw Data',
                    title2='PCA Embedding',
                    title3='VAE Embedding',
                    modelname=model_name,
                    dataset_name=dataset_name,
                    output_dir=output_dir
                )
            except Exception as e:
                print(f'      Error plotting three-way comparison: {e}')
                import traceback
                traceback.print_exc()
        else:
            print(f'    Error: Need all three UMAP types (Raw, PCA, VAE), but only found {list(available_umaps.keys())}')
    else:
        print(f'    Error: Need at least 3 UMAP types, but only found {len(available_umaps)}')


def process_all_model_data(model_data_dir='model_data', output_dir='images/umaps'):
    """
    Process all ModelData files in a directory.
    
    Args:
        model_data_dir: Directory containing pickled ModelData files
        output_dir: Output directory for images
    """
    model_data_path = Path(model_data_dir)
    model_files = list(model_data_path.glob('model_*.pkl'))
    
    print(f'Found {len(model_files)} model data files to process')
    
    for model_file in model_files:
        try:
            process_model_data(
                model_data_path=str(model_file),
                output_dir=output_dir
            )
        except Exception as e:
            print(f'Error processing {model_file}: {e}')
            import traceback
            traceback.print_exc()
            continue


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description='Generate three-way UMAP visualization plots')
    parser.add_argument('--model_data', type=str, help='Path to pickled ModelData file')
    parser.add_argument('--model_data_dir', type=str, default='model_data', help='Directory containing ModelData files')
    parser.add_argument('--all', action='store_true', help='Process all ModelData files in model_data_dir')
    parser.add_argument('--output_dir', type=str, default='images/umaps', help='Output directory for images')
    
    args = parser.parse_args()
    
    if args.all:
        process_all_model_data(
            model_data_dir=args.model_data_dir,
            output_dir=args.output_dir
        )
    elif args.model_data:
        process_model_data(
            model_data_path=args.model_data,
            output_dir=args.output_dir
        )
    else:
        parser.print_help()
        print('\nError: Must specify either --model_data or --all')

